highligher: pygments
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
assets:
  sources:
    - _assets
    - _assets/fonts
kramdown:
  input: GFM